version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - duels_miniapp_api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/static/www:/var/www/static

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  duels_miniapp_api:
    image: duels-miniapp-api
    volumes:
      - ./logs:/app/logs
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
  mongo:
    image: mongo:4.2.3-bionic
    expose:
      - 27017
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./data/mongo:/data/db
    env_file:
      - mongo.env
volumes:
  mongo-duels: