version: '3'

services:
  api:
    image: duels-miniapp-api
    ports:
      - "127.0.0.1:5002:5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
  mongo:
    image: mongo:4.2.3-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    env_file:
      - mongo.env
volumes:
  mongo-duels: